### ISSUE TITLE
Variables and Primitive Data Types

### ISSUE THREAD

**Issue by kovalshmidt** [kovalshmidt/javacourse#2]
- [x] Read about Variables here: https://docs.oracle.com/javase/tutorial/java/nutsandbolts/variables.html

- [x] Read about Primitive Data Types here: https://docs.oracle.com/javase/tutorial/java/nutsandbolts/datatypes.html

**Comment by Martneb** [comment]
// The number 26, in binary
int binVal = 0b11010
-> Doesnt seem to add up to 26, only 11

Dont eally get Literals, or at least what they are neccesary for (For what purpose?)
