### ISSUE TITLE
Nested Classes

### ISSUE THREAD

**Issue by kovalshmidt** [kovalshmidt/javacourse#27]
- [x] Nested Classes: https://docs.oracle.com/javase/tutorial/java/javaOO/nested.html

- [x] Inner Classes: https://docs.oracle.com/javase/tutorial/java/javaOO/innerclasses.html

- [x] Local Classes: https://docs.oracle.com/javase/tutorial/java/javaOO/localclasses.html

- [x] Anonymous Classes: https://docs.oracle.com/javase/tutorial/java/javaOO/anonymousclasses.html

- [x] When to use which kind of class: https://docs.oracle.com/javase/tutorial/java/javaOO/whentouse.html

**Comment by Martneb** [comment]
Dont really get nested classes, especially how they differ in look from regular methods

same for local and annonymus classes

**Comment by Martneb** [comment]
same for local and annonymus classes
