### ISSUE TITLE
Invoice

### ISSUE THREAD

**Issue by kovalshmidt** [kovalshmidt/javacourse#6]
To compete this assignment in **exercises** create a package called **invoice** where you will have two calsses Invoice and InvoiceTest

_**(Invoice Class)** Create a class called **Invoice** that a hardware store might use to represent an invoice for an item sold at the store. An Invoice should include four pieces of information as instance variables—a part number (type String), a part description (type String), a quantity of the item being purchased (type int) and a price per item (double). Your class should have a constructor that initializes the four instance variables. Provide a set and a get method for each instance variable. In addition, provide a method named getInvoiceAmount that calculates the invoice amount (i.e., multiplies the quantity by the price per item), then returns the amount as a double value. If the quantity is not positive, it should be set to 0. If the price per item is not positive, it should be set to 0.0. Write a test app named **InvoiceTest** that demonstrates class Invoice’s capabilities._

**Comment by Martneb** [comment]
How do you delete unwanted files from the Github depository?

**Comment by kovalshmidt** [comment]
> How do you delete unwanted files from the Github depository?

You delete them locally and when you push they are removed from Github repository too

**Comment by kovalshmidt** [comment]
_"If the quantity is not positive, it should be set to 0. If the price per item is not positive, it should be set to 0.0. "_
Adjust the code to satisfy this request condition
