### ISSUE TITLE
Eight Queens

### ISSUE THREAD

**Issue by kovalshmidt** [kovalshmidt/javacourse#62]
A puzzler for chess buffs is the Eight Queens problem, which asks: Is it possible to place eight queens on an empty chessboard so that no queen is “attacking” any other (i.e., no two queens are in the same row, in the same column or along the same diagonal)? For instance, if a queen is placed in the upper-left corner of the board, no other queens could be placed in any of the marked squares shown in Fig. 18.20. Solve the problem recursively. [Hint: Your solution should begin with the first column and look for a location in that column where a queen can be placed— initially, place the queen in the first row. The solution should then recursively search the remaining columns. In the first few columns, there will be several locations where a queen may be placed. Take the first available location. If a column is reached with no possible location for a queen, the program should return to the previous column, and move the queen in that column to a new row. This continuous backing up and trying new alternatives is an example of recursive backtracking.]

**Comment by Martneb** [comment]
Figures 18.20 are missing

**Comment by kovalshmidt** [comment]
<img width="210" alt="Screenshot 2020-05-29 at 18 56 02" src="https://user-images.githubusercontent.com/28290808/83279633-111ac480-a1de-11ea-8363-85880f5275f8.png">
