### ISSUE TITLE
Exceptions

### ISSUE THREAD

**Issue by kovalshmidt** [kovalshmidt/javacourse#72]
https://docs.oracle.com/javase/tutorial/essential/exceptions/index.html
<img width="182" alt="Screenshot 2020-06-15 at 12 03 18" src="https://user-images.githubusercontent.com/28290808/84638911-49b9de00-af00-11ea-8518-653c38bbbf68.png">

**Comment by Martneb** [comment]
I believe you pasted the wrong link: https://docs.oracle.com/javase/tutorial/essential/exceptions/
