### ISSUE TITLE
Constructor Failure

### ISSUE THREAD

**Issue by kovalshmidt** [kovalshmidt/javacourse#77]
Write a program that shows a constructor passing information about constructor failure to an exception handler. Define class SomeClass, which throws an Exception in the constructor. Your program should try to create an object of type SomeClass and catch the exception that’s thrown from the constructor.

**Comment by Martneb** [comment]
public class ConstructorFailure {
    public Exception1()throws Exception
    {
        throw new Exception();
    }

    public static void main(String[] args) {
        try{

            Exception1 e = new Exception1();
        }catch(Exception exception)
        {
            System.out.println("Exception type: " + exception);
        }
    }
}



Error:(10, 12) java: invalid method declaration; return type required

**Comment by kovalshmidt** [comment]
The constructor should have the same name as the class name

<img width="689" alt="Screenshot 2020-07-03 at 11 05 12" src="https://user-images.githubusercontent.com/28290808/86446797-1b6c3900-bd1d-11ea-8b4d-2d4381f1cf94.png">
