### ISSUE TITLE
Install and configure MYSQL Server And Workbench

### ISSUE THREAD

**Issue by kovalshmidt** [kovalshmidt/javacourse#86]
On your laptop install MySQL Server and Workbench 
https://dev.mysql.com/downloads/

**Comment by Martneb** [comment]
How do i install the server?  it just gave me a zip file

**Comment by kovalshmidt** [comment]
> How do i install the server? it just gave me a zip file

https://www.youtube.com/watch?v=u96rVINbAUI&t=258s
