### ISSUE TITLE
Account

### ISSUE THREAD

**Issue by kovalshmidt** [kovalshmidt/javacourse#9]
In **excercises** write a separate package for this assignment called **account**

_Create a class named **Account** with fields **name** (String), **balance** (double) and methods to **deposit** money on the account and a method to **withdraw** them. Make sure that you cannot withdraw more than there is on the accounts balance and you can't deposit an amount that is not positive.
Write a test app named **AccountTest** that demonstrates the Account class capabilities, create several accounts and perform several transfers from one account to the other and  the other way around. 
You can make use of Scanner to perform a similar functionality that has ah ATM machine. Choose the account, choose the amount to withdraw or transfer, in case of the last choose to which account_

**Comment by Martneb** [comment]
How do i get an account (acc[0]-acc[4]) by putting the name in ?

**Comment by kovalshmidt** [comment]
describe the case when you need to get it
from what you show it looks like it is an account array, right?

**Comment by Martneb** [comment]
String nameCheck1 = input.next();
        while (counter < 5) {
            if (acc[counter].name.equals(nameCheck1)) {
                 owner = counter;}
                System.out.println("test");
            ++counter;
        }

i want to check if the input matches any of the acc[x].name in the array, but it seems the if-order is never checked and therefore the owner is never selected.
acc[counter].name.equals(nameCheck1) should check for the input but it just doesn't do it

if you could check what causes it to not to check or to check it as false i would be very thankful

**Comment by kovalshmidt** [comment]
push the code I will check it there

**Comment by kovalshmidt** [comment]
you can write in the commit "In progress #9"

**Comment by Martneb** [comment]
is there with comment "proto version"

**Comment by Martneb** [comment]
Error when typing in target account for [Transfer]:
Exception in thread "main" java.util.InputMismatchException
	at java.util.Scanner.throwFor(Scanner.java:864)
	at java.util.Scanner.next(Scanner.java:1485)
	at java.util.Scanner.nextDouble(Scanner.java:2413)
	at Lesson_1.Excercises.AccountPackage.AccountTest.main(AccountTest.java:67)

Target: Lana Yang

also the main banking part is skipping the first loop when typing in any of the account names but not when you type in any other string, like "d"

**Comment by kovalshmidt** [comment]
we will have a look at it in the evening
